### ISSUE TITLE
JOSS reviewer comments

### ISSUE THREAD

**Issue by craddm** [jorittmo/singcar#2]
Hi there,

This is my review for [JOSS](https://github.com/openjournals/joss-reviews/issues/3887).

It's a nice short one, I think. This seems to me a really nice well-documented package. Installed fine from both CRAN and Github, everything I've tried to do with it has worked, and it seems to have appropriate automated tests set up. The manuscript does a good job of covering the need for the package. All in all I think it's a really nice contribution.

The only thing I can comment on is regarding **Community Guidelines**, which are required by JOSS. Add some additional guidance for people who, as per the review criteria, wish to "1) Contribute to the software 2) Report issues or problems with the software 3) Seek support". See [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) - might be a bit overkill for your needs, but at least get a `contributing.md` with some simple info, and maybe add something in the `readme` file pointing people at the issue tracker etc. A good way to look for ideas is to look at some of the recently accepted JOSS articles through their issue tracker!

Cheers,
Matt

**Comment by jorittmo** [comment]
Setting up some community guidelines is absolutely something I should do, just did not occur to me for some reason. Thank you very much for the review, I appreciate your work!

Best

**Comment by lindemann09** [comment]
Hi,

This is my short review for [JOSS](https://github.com/openjournals/joss-reviews/issues/3887). Sorry for my delayed response.

With `singcar` your provide a very nice, well-documented and stable R packages. The manuscript is clear-cut.  I'm convinced that the package is highly needed and very useful for researcher and neuropsychologists working with single case data.

The only critical issue that I see has already been raised by @craddm (see above) and is related to the of missing community guidelines. I find it particularly relevant to clarify how to report issues or problems with the software (2).

cheers,
Oliver

**Comment by jorittmo** [comment]
In commit [386af4c](https://github.com/jorittmo/singcar/commit/386af4c5913b4f7abd9a18cc98d79b2120a3c4bc) I have now addressed the lack of both contribution guidelines and a code of conduct by including a [contribution.md](https://github.com/jorittmo/singcar/blob/master/CONTRIBUTING.md) and [code_of_conduct.md](https://github.com/jorittmo/singcar/blob/master/CODE_OF_CONDUCT.md) (as well as pointing to them in the README). 

Thank you both for the reviews!
